apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-script
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bumipl/java-script.git'
    targetRevision: HEAD
    path: 'kubernetes'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
